include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME = opal
SUBPROJECTS = \
	OpalGraphics\
	OpalText

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
-include GNUmakefile.postamble
